language: node_js

dist: jammy

cache:
  npm: false

stages:
  - name: Build-Test
  - name: Semantic-Release
    if: (branch = main) AND (type IN (push, api)) AND (fork = false)

# Default "script" step.
script:
- npm run build
- npm run test-unit-travis || travis_terminate 1
- npm run lint
- npm run check-packages

jobs:
  include:
    - stage: Build-Test
      language: node_js
      node_js: 18
    - node_js: 20
    - node_js: 22

    - stage: Semantic-Release
      language: node_js
      node_js: 22
      script:
        - npm run semantic-release